export const SEARCH_MOVIES_REQUEST = 'SEARCH_MOVIES_REQUEST'
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS'
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE'

export const SEARCH_SHOWS_REQUEST = 'SEARCH_SHOWS_REQUEST'
export const SEARCH_SHOWS_SUCCESS = 'SEARCH_SHOWS_SUCCESS'
export const SEARCH_SHOWS_FAILURE = 'SEARCH_SHOWS_FAILURE'
